# Generated by Django 4.2.3 on 2023-08-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStroeModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('author_email', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('History', 'History'), ('Database', 'Database'), ('Operatng System', 'Operatng System'), ('Mystrey', 'Mystrey')], max_length=50)),
                ('first_publication', models.DateTimeField(auto_now_add=True)),
                ('last_publication', models.DateTimeField()),
                ('publish_country', models.CharField(max_length=30)),
            ],
        ),
    ]
